name: commitlint
on: [push, pull_request]

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Commitlint
        uses: remarkablemark/commitlint@c4f9e77786e0c94d17570ed36be2adcf022711d3 # v2
        with:
          checkout: true
